# Generated by Django 2.2.5 on 2019-09-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True)),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('turnover', models.FloatField(default=0.0)),
                ('share_traded', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
